In [1]:
import torch
import time
import numpy as np
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
%%time
start_time = time.time()
#mat ops
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0003063679
CPU times: user 710 μs, sys: 0 ns, total: 710 μs
Wall time: 499 μs


In [3]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = np.random.rand(10000, 10000)
np_rand2 = np.random.rand(10000, 10000)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00756669
0.17876911


In [4]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [5]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out                                                                            

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2,3,4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [11]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias = False)
print(linear(sample))

tensor([  9.5808, -11.0334,  -0.7948], grad_fn=<SqueezeBackward4>)


In [13]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [14]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)
input_indices = torch.LongTensor([1, 5, 3, 2])
embedded_output = embedding(input_indices)

print(embedded_output.shape)

torch.Size([4, 100])


In [15]:
int_64 = torch.randint(1, (3, 2)).float()
float_32 = torch.rand(2, 3)

print(int_64)


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [16]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape
print(a)
a = a.view(x, y, z)
print(a)
print(a.shape)

tensor([[[0.9829, 0.2287, 0.8190, 0.2642, 0.2198],
         [0.7137, 0.5521, 0.1387, 0.8849, 0.6334],
         [0.7150, 0.2274, 0.4337, 0.3011, 0.2876]],

        [[0.9956, 0.6612, 0.4944, 0.9731, 0.2813],
         [0.9945, 0.8274, 0.7852, 0.3405, 0.5349],
         [0.5037, 0.4465, 0.6894, 0.7832, 0.3350]]])
tensor([[[0.9829, 0.2287, 0.8190, 0.2642, 0.2198],
         [0.7137, 0.5521, 0.1387, 0.8849, 0.6334],
         [0.7150, 0.2274, 0.4337, 0.3011, 0.2876]],

        [[0.9956, 0.6612, 0.4944, 0.9731, 0.2813],
         [0.9945, 0.8274, 0.7852, 0.3405, 0.5349],
         [0.5037, 0.4465, 0.6894, 0.7832, 0.3350]]])
torch.Size([2, 3, 5])


In [21]:
x = torch.tensor([10], dtype=torch.float32)
print(x)
y = F.tanh(x)
print(y)

tensor([10.])
tensor([1.])
